### ISSUE TITLE
I'm searching for THAT FMsel which is provided with Dark Engine

### ISSUE THREAD

**Issue by ANGulchenko** [Xanfre/fmsel#1]
FMSel really could use some polish ( for example it doesn't look good on 4k monitors) but I'm not sure where the code is... Is it THAT FMSel or just a fork?

**Comment by Xanfre** [comment]
This is the original FMSel provided with NewDark, yes. The initial commit here is equivalent to the distribution included with the 1.27 binaries. However, this is a fork in the sense that it has been modified from its original form. This repository includes a few minor improvements, notably tweaking the window behavior and implementing the ability to automatically generate missing mission flags like other loaders.

There is already a font size option included (see Settings -> UI Font Size), but there are only two options and the "large" size may still be too small for some high-resolution displays. FLTK is not really designed to handle the automatic resizing of fonts within widgets, so accomplishing arbitrary font scaling would require writing custom resizing logic. That said, another much simpler option would be to just scale the entire window, which would respect the layout of the widgets and should make their text more readable.

I just published a [release](https://github.com/Xanfre/fmsel/releases) including this change. You should find the new scaling options in Settings -> UI Scale. Currently, scales from 1 to 2 in increments of 0.25 are supported, though this could be further expanded if necessary. Is something like this what you had in mind?

**Comment by ANGulchenko** [comment]
>Is something like this what you had in mind?

Yes, but I would like to see it in the standard Dark Engine release. That was the point. As I understand your patches won't appear there?

**Comment by Xanfre** [comment]
No, these changes are not being distributed with the NewDark binaries themselves, though the NewDark distributors are free to take or use them. The original FMSel release has not seen an update in quite some time, however.
